In [1]:
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\arazs\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [2]:
# import stuff
%load_ext autoreload
%autoreload 2
%matplotlib inline

from random import randint

import numpy as np
import torch

## Load model

In [20]:
# Load model
from models import InferSent
model_version = 1
MODEL_PATH = "encoder/infersent%s.pkl" % model_version
params_model = {'bsize': 64, 'word_emb_dim': 300, 'enc_lstm_dim': 2048,
                'pool_type': 'max', 'dpout_model': 0.0, 'version': model_version}
model = InferSent(params_model)
model.load_state_dict(torch.load(MODEL_PATH))

<All keys matched successfully>

In [21]:
# Keep it on CPU or put it on GPU
use_cuda = True
model = model.cuda() if use_cuda else model

In [22]:
# If infersent1 -> use GloVe embeddings. If infersent2 -> use InferSent embeddings.
W2V_PATH = 'GloVe/glove.840B.300d.txt' if model_version == 1 else 'fastText/crawl-300d-2M.vec'
model.set_w2v_path(W2V_PATH)

In [23]:
# Load embeddings of K most frequent words
model.build_vocab_k_words(K=100000)

Vocab size : 100000


### Updating Model with Vocab from our Dataset

In [25]:
all_para_sentences = []
for para in data:
    all_para_sentences.extend(para)

In [27]:
len(all_para_sentences)

6575

In [28]:
model.update_vocab(all_para_sentences)

Found 1401(/1972) words with w2v vectors
New vocab size : 101816 (added 1401 words)


In [29]:
all_q_sentences = []
for para in data_qs:
    all_q_sentences.extend(para)

In [31]:
model.update_vocab(all_q_sentences)

Found 121(/293) words with w2v vectors
New vocab size : 101937 (added 121 words)


## Load sentences

### Trying with MultiRC Dataset

In [7]:

f = open("Paragraphs.json","r",encoding="utf8")
data = json.load(f)
print(len(data))

456


In [8]:

f = open("Questions.json","r",encoding="utf8")
data_qs = json.load(f)
print(len(data_qs))

456


In [32]:
Para_Embeddings = []

In [33]:
for para in data:
  para_embed = model.encode(para)
  print((para_embed))
  Para_Embeddings.append(para_embed)

C:\Users\arazs\Documents\GitHub\InferSent\models.py:207: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  sentences = np.array(sentences)[idx_sort]


[[ 0.11256243  0.09040198  0.0365129  ...  0.          0.
   0.        ]
 [ 0.08737183  0.1160657   0.11471046 ...  0.00090266  0.
   0.01330047]
 [ 0.0961346   0.07750011  0.13451654 ...  0.          0.
   0.00076486]
 ...
 [ 0.04519949  0.02378928  0.00222661 ...  0.          0.
   0.        ]
 [ 0.0420932   0.07437453  0.         ...  0.          0.
   0.01302759]
 [ 0.1645855   0.11042652  0.12777373 ...  0.06823937 -0.03814263
  -0.01091907]]
[[ 0.13017015  0.12825833  0.10208301 ...  0.0449623   0.
   0.01596533]
 [ 0.1303148   0.19024482  0.13078132 ...  0.0609626   0.
   0.03200877]
 [ 0.11340217  0.13293453  0.05816589 ...  0.11457216  0.
   0.02241952]
 ...
 [ 0.14254619  0.20428835  0.10164339 ...  0.11937881 -0.03814263
   0.07896413]
 [ 0.15406513  0.19931452  0.12465417 ...  0.09522928  0.
   0.05935117]
 [ 0.04341318  0.09296721  0.06162942 ...  0.01124588  0.
   0.04815275]]
[[0.08997444 0.18418273 0.06180476 ... 0.         0.         0.10357223]
 [0.01546932 0.11675488

[[0.08195855 0.07108551 0.09474102 ... 0.         0.         0.15524845]
 [0.13404034 0.10306878 0.16485506 ... 0.         0.         0.05618284]
 [0.12369319 0.11787507 0.320627   ... 0.05428101 0.         0.        ]
 ...
 [0.12483554 0.         0.06866399 ... 0.         0.         0.03563702]
 [0.02964286 0.12692337 0.0333989  ... 0.         0.00373779 0.        ]
 [0.06885618 0.08767831 0.02414497 ... 0.05842281 0.         0.08982687]]
[[0.0824357  0.05452994 0.02569418 ... 0.02152194 0.         0.14892206]
 [0.05929901 0.         0.         ... 0.         0.         0.        ]
 [0.         0.08309527 0.19192606 ... 0.09395886 0.         0.07757204]
 ...
 [0.10973963 0.09264307 0.09220994 ... 0.02979544 0.0096184  0.1109168 ]
 [0.03388035 0.12541609 0.02506596 ... 0.         0.         0.07305411]
 [0.04823475 0.18017349 0.06021751 ... 0.21062861 0.         0.00423823]]
[[0.04242317 0.09951209 0.08473574 ... 0.08135092 0.         0.06275687]
 [0.06884048 0.         0.14464171 ... 

[[0.0182737  0.05433253 0.06206239 ... 0.         0.         0.08833628]
 [0.08054427 0.15733007 0.13426985 ... 0.20121425 0.         0.12107975]
 [0.02716731 0.02347423 0.03293387 ... 0.         0.         0.07709485]
 ...
 [0.12408795 0.06922981 0.17321563 ... 0.         0.         0.00937811]
 [0.07775933 0.07484798 0.05292077 ... 0.01336982 0.         0.        ]
 [0.05416057 0.05709263 0.12223606 ... 0.00119007 0.02686724 0.12866884]]
[[ 0.11404397  0.23324063  0.11610592 ...  0.08540387  0.
   0.05113541]
 [ 0.06479701  0.10649399  0.14518794 ...  0.05385767 -0.03814263
   0.15040427]
 [ 0.0818991   0.12602086  0.0429122  ...  0.08016574  0.
   0.        ]
 ...
 [ 0.15096235  0.18747497  0.12471325 ...  0.10806747  0.06980749
   0.        ]
 [ 0.04024624  0.04571805  0.0694982  ...  0.          0.
   0.        ]
 [ 0.0721503   0.12514041  0.0669819  ...  0.11275563  0.
   0.08429978]]
[[ 0.07362642  0.12261932  0.06068937 ...  0.03406104  0.
   0.07017533]
 [ 0.08824945  0.109688

[[0.07883009 0.16289473 0.09561199 ... 0.01632869 0.         0.06902518]
 [0.13348462 0.07789117 0.06581316 ... 0.04866718 0.0453878  0.        ]
 [0.07283948 0.13065973 0.04956153 ... 0.00495011 0.08094209 0.08572941]
 ...
 [0.06314491 0.18775699 0.05072599 ... 0.02383985 0.06266391 0.09189229]
 [0.05987185 0.22385381 0.02969334 ... 0.17795795 0.         0.05598975]
 [0.09863328 0.17123318 0.14000155 ... 0.13185214 0.06840011 0.00549719]]
[[0.04548664 0.19215782 0.1709632  ... 0.09300804 0.         0.09758569]
 [0.05308564 0.13722278 0.01740665 ... 0.05711279 0.         0.0827262 ]
 [0.07127562 0.09699831 0.06204746 ... 0.08570855 0.         0.10796627]
 [0.04184123 0.06605733 0.09859183 ... 0.02549334 0.         0.17152682]
 [0.02590156 0.12071372 0.02147545 ... 0.08540387 0.         0.1087042 ]
 [0.0726032  0.12545788 0.10966774 ... 0.09669779 0.01912871 0.13087735]]
[[0.         0.         0.00640664 ... 0.         0.         0.        ]
 [0.04756519 0.04924486 0.10496488 ... 0.020

[[0.02863096 0.05412726 0.01389194 ... 0.         0.         0.01361017]
 [0.05155129 0.15137747 0.04896777 ... 0.11501389 0.         0.07635248]
 [0.08729329 0.10289838 0.03654315 ... 0.06216284 0.         0.03140707]
 ...
 [0.03432062 0.10789306 0.09913678 ... 0.16835245 0.         0.11117407]
 [0.03489815 0.071008   0.08409792 ... 0.         0.         0.06498478]
 [0.05919994 0.11953636 0.02174351 ... 0.04128607 0.         0.09310159]]
[[0.10599775 0.09998567 0.02976484 ... 0.08639067 0.         0.        ]
 [0.03621829 0.06384008 0.09298975 ... 0.00614962 0.         0.1178163 ]
 [0.06055411 0.05787226 0.08045122 ... 0.         0.         0.11640283]
 ...
 [0.12308002 0.10371245 0.13146558 ... 0.06987547 0.         0.06123373]
 [0.15848775 0.0597503  0.12917176 ... 0.00027865 0.         0.        ]
 [0.11115922 0.07774543 0.19030003 ... 0.04161864 0.         0.        ]]
[[ 0.06239373  0.10564385  0.11179203 ...  0.          0.
   0.08553986]
 [ 0.06482314  0.12083509  0.09227373 .

[[0.11451773 0.20003898 0.13056006 ... 0.01446818 0.         0.16440703]
 [0.05488851 0.11809888 0.1527546  ... 0.         0.         0.        ]
 [0.07218607 0.15044409 0.20155163 ... 0.12855884 0.         0.18410674]
 ...
 [0.03330296 0.10587128 0.069931   ... 0.05007476 0.         0.02507438]
 [0.09045292 0.07561744 0.04176349 ... 0.0273295  0.         0.03087726]
 [0.01848564 0.         0.         ... 0.         0.         0.        ]]
[[0.02805532 0.         0.02440123 ... 0.00055291 0.         0.01731869]
 [0.04865982 0.12026907 0.07860218 ... 0.         0.         0.06017051]
 [0.07583146 0.04092078 0.05312611 ... 0.         0.         0.10012875]
 ...
 [0.03779769 0.06520583 0.04951167 ... 0.         0.         0.04206009]
 [0.07363163 0.03592175 0.0975917  ... 0.         0.03375169 0.05062604]
 [0.02468351 0.0679009  0.03972642 ... 0.00801639 0.         0.02756222]]
[[0.05112366 0.09165674 0.13251105 ... 0.05093015 0.         0.05738901]
 [0.07969307 0.0927045  0.08609926 ... 

[[ 0.10044773  0.20319717  0.02232626 ...  0.09953674  0.
   0.05308989]
 [ 0.08499799  0.16084933  0.01962587 ...  0.02509381  0.
   0.03580995]
 [ 0.10633262  0.1936246   0.         ...  0.18085827  0.
   0.02174607]
 ...
 [ 0.05834034  0.14213444  0.03678767 ...  0.0544364   0.
   0.05785291]
 [ 0.08499799  0.12623417  0.02318291 ...  0.02752832  0.
   0.04191844]
 [ 0.03225289  0.22513211  0.0537575  ...  0.13209501 -0.03814263
   0.02816033]]
[[ 0.07247724  0.12729688  0.07434613 ...  0.05597548  0.
   0.02618148]
 [ 0.0889906   0.09458695  0.03484443 ...  0.03496604  0.
   0.01798309]
 [ 0.07360736  0.12638807  0.12447491 ...  0.08889406 -0.0041413
   0.04858736]
 ...
 [ 0.1260407   0.1251801   0.07858613 ...  0.0411891   0.
   0.01883504]
 [ 0.00755471  0.0854902   0.06755723 ...  0.          0.
   0.14892463]
 [ 0.04358257  0.22058967  0.06678683 ...  0.13688292  0.
   0.04505259]]
[[0.0772923  0.07358566 0.09309372 ... 0.01898208 0.         0.        ]
 [0.06370076 0.14877087 

[[0.09796324 0.15780202 0.09349082 ... 0.         0.02962599 0.02237963]
 [0.09105764 0.09828024 0.12999193 ... 0.04595824 0.         0.04087408]
 [0.08514619 0.10719522 0.11681913 ... 0.06804791 0.         0.05391913]
 ...
 [0.07048884 0.12184405 0.09270056 ... 0.03383761 0.         0.07359104]
 [0.04563449 0.05648314 0.07231249 ... 0.         0.         0.02719685]
 [0.12635149 0.05313782 0.09500406 ... 0.04619408 0.         0.0688055 ]]
[[0.00935484 0.08489619 0.09222756 ... 0.06496157 0.         0.04616182]
 [0.118249   0.0939487  0.13079369 ... 0.02654784 0.         0.07019423]
 [0.09766089 0.0983689  0.11878592 ... 0.         0.         0.07064241]
 ...
 [0.07354403 0.0985161  0.06538709 ... 0.         0.         0.        ]
 [0.06399752 0.05175171 0.06327412 ... 0.         0.         0.01958333]
 [0.14639422 0.10504432 0.05279252 ... 0.         0.01868074 0.00593813]]
[[0.03050682 0.13028619 0.1196619  ... 0.         0.         0.        ]
 [0.07538426 0.17948389 0.10039473 ... 

[[0.12560011 0.11730168 0.14567241 ... 0.07094589 0.         0.        ]
 [0.06160672 0.17441395 0.11765768 ... 0.04893791 0.         0.02320319]
 [0.06499284 0.10156923 0.08524337 ... 0.00853007 0.00675449 0.03043111]
 ...
 [0.13145973 0.1179878  0.14321978 ... 0.05860957 0.         0.10226627]
 [0.10598459 0.12843336 0.0793438  ... 0.01769321 0.         0.0304311 ]
 [0.07883258 0.06619515 0.14670704 ... 0.01636881 0.         0.        ]]
[[ 0.06590181  0.20231171  0.12530518 ...  0.          0.
   0.07574899]
 [ 0.05326049  0.2557706   0.07012258 ...  0.          0.
   0.        ]
 [ 0.0423507   0.2583573   0.05702182 ...  0.          0.
   0.0230166 ]
 ...
 [ 0.09062332  0.19513124  0.         ...  0.          0.
   0.        ]
 [ 0.06653449  0.25458464  0.06959485 ...  0.02763702 -0.03509309
   0.07874288]
 [ 0.04748468  0.29196623  0.04139975 ...  0.          0.
   0.        ]]
[[0.12738656 0.06872772 0.07082321 ... 0.04061666 0.         0.01326919]
 [0.15515424 0.11174553 0.13043

[[0.07883009 0.17099303 0.12664843 ... 0.17766511 0.         0.05090274]
 [0.10452662 0.21092494 0.22618836 ... 0.07738555 0.         0.00944096]
 [0.01404656 0.0825334  0.23569389 ... 0.         0.         0.04137722]
 ...
 [0.07513876 0.18178864 0.15176924 ... 0.         0.         0.03641048]
 [0.06044872 0.16929558 0.14265119 ... 0.01604114 0.         0.01659155]
 [0.04748904 0.1438938  0.14735979 ... 0.         0.         0.09345332]]
[[0.06406685 0.12267339 0.05729971 ... 0.06423842 0.         0.        ]
 [0.07151408 0.09734043 0.         ... 0.04110578 0.         0.04087724]
 [0.10859683 0.19214535 0.09718996 ... 0.03567299 0.01851953 0.00056302]
 ...
 [0.07747864 0.07810915 0.10393357 ... 0.         0.         0.        ]
 [0.09748405 0.12820084 0.1732222  ... 0.         0.05939081 0.05782088]
 [0.07629729 0.12727788 0.         ... 0.         0.01868075 0.        ]]
[[ 0.08142463  0.09383707  0.08542957 ...  0.03057024  0.
   0.07833128]
 [ 0.06599758  0.07348772  0.03032917 .

[[0.04980839 0.11295043 0.09073479 ... 0.01736926 0.         0.08029858]
 [0.05211741 0.1175806  0.05894851 ... 0.09262641 0.         0.01412125]
 [0.05503113 0.08600826 0.13863835 ... 0.04422576 0.         0.06906762]
 ...
 [0.04338232 0.20109192 0.08575001 ... 0.26115492 0.         0.11681873]
 [0.0666656  0.20466644 0.08455432 ... 0.25485298 0.03854677 0.15247294]
 [0.07249334 0.06223403 0.07577378 ... 0.07828046 0.         0.        ]]
[[0.12220048 0.07504613 0.17378722 ... 0.10503106 0.         0.        ]
 [0.04276178 0.14493814 0.08327927 ... 0.06155197 0.         0.09240179]
 [0.00770968 0.08464561 0.07281667 ... 0.12611885 0.02565456 0.05847434]
 ...
 [0.03691937 0.14636283 0.05801239 ... 0.01232972 0.00339961 0.08971625]
 [0.04222273 0.11524413 0.05556459 ... 0.0886512  0.         0.03973796]
 [0.03248564 0.07212111 0.06812575 ... 0.12234379 0.         0.13275138]]
[[0.06561071 0.10224976 0.10572828 ... 0.         0.         0.12616101]
 [0.04930793 0.07489416 0.0682265  ... 

[[0.06620653 0.08267977 0.         ... 0.03217987 0.         0.        ]
 [0.08273333 0.07861962 0.05414009 ... 0.         0.         0.01851055]
 [0.02250842 0.06973099 0.03829511 ... 0.         0.         0.00594683]
 ...
 [0.03328361 0.06181281 0.00734465 ... 0.         0.         0.        ]
 [0.02767067 0.09705403 0.0416058  ... 0.         0.         0.        ]
 [0.12291346 0.10647145 0.00428684 ... 0.         0.         0.03502196]]
[[0.06028822 0.18264513 0.         ... 0.21886164 0.         0.03112485]
 [0.0546014  0.06920369 0.08556396 ... 0.07777306 0.         0.01683964]
 [0.08748768 0.05600135 0.1235239  ... 0.09446035 0.         0.03086132]
 ...
 [0.0469228  0.07511195 0.1407354  ... 0.0196795  0.         0.048285  ]
 [0.14513654 0.07649884 0.0947484  ... 0.03293483 0.         0.01375628]
 [0.08300737 0.09672324 0.1876169  ... 0.03730594 0.         0.017178  ]]
[[0.15654996 0.09596877 0.02552139 ... 0.02850552 0.         0.14709845]
 [0.07124432 0.09666871 0.1553946  ... 

[[ 0.11407362  0.19155413  0.14450997 ...  0.2024398   0.03315686
   0.13752897]
 [ 0.10201494  0.07989875  0.08816949 ...  0.10231314 -0.03814263
   0.02440172]
 [ 0.06393925  0.00076694  0.11807431 ...  0.09666333  0.
   0.143508  ]
 ...
 [ 0.06204235  0.07963888  0.23314577 ...  0.07209627  0.
   0.08335195]
 [ 0.00953631  0.03470108  0.03673842 ...  0.          0.
   0.03317643]
 [ 0.10570779  0.04697511  0.0646636  ...  0.02906301  0.
   0.01918543]]
[[0.04456575 0.15242301 0.06369121 ... 0.13263679 0.         0.06585667]
 [0.10685061 0.13387328 0.06931973 ... 0.07083158 0.01916508 0.0075506 ]
 [0.11215778 0.1290832  0.10595852 ... 0.07229089 0.         0.00314567]
 ...
 [0.06245186 0.02722037 0.04464227 ... 0.         0.         0.        ]
 [0.04296533 0.15596175 0.08182097 ... 0.01704106 0.         0.00732132]
 [0.0707876  0.12351088 0.10733989 ... 0.05519324 0.00653162 0.01711597]]
[[0.03404962 0.14898247 0.07212819 ... 0.         0.04776326 0.        ]
 [0.06996203 0.01182725

[[0.07883009 0.12164836 0.0399672  ... 0.05478676 0.         0.10598988]
 [0.02781615 0.07968035 0.10008312 ... 0.13995093 0.         0.04474173]
 [0.0414269  0.07994328 0.05618222 ... 0.07157334 0.         0.        ]
 ...
 [0.12322249 0.13356848 0.0308109  ... 0.05542035 0.         0.04233598]
 [0.06054907 0.12187254 0.14503843 ... 0.04918384 0.         0.1235274 ]
 [0.08843575 0.09382407 0.10266033 ... 0.09695951 0.         0.07030777]]
[[0.04801315 0.18599676 0.11529387 ... 0.04942515 0.         0.12408084]
 [0.09376144 0.08602887 0.11252606 ... 0.         0.         0.        ]
 [0.07343707 0.07588319 0.00125167 ... 0.         0.         0.02394027]
 ...
 [0.07531647 0.06805529 0.04391971 ... 0.         0.         0.06985145]
 [0.05629662 0.08418152 0.04209542 ... 0.12149077 0.         0.06184747]
 [0.06524735 0.07388748 0.07501544 ... 0.04704941 0.         0.05405254]]
[[0.04133107 0.10590491 0.08482672 ... 0.00577812 0.03628632 0.02734583]
 [0.10505588 0.12045781 0.15385605 ... 

[[ 0.08489597  0.05582239  0.04936203 ...  0.05692964  0.
   0.08056387]
 [ 0.06716632  0.08238188  0.13447878 ...  0.05045628  0.
   0.07613651]
 [ 0.14562513  0.09273078  0.11628772 ...  0.06809468 -0.03814263
   0.1407492 ]
 ...
 [ 0.02420504  0.11790023  0.06285957 ...  0.          0.02565757
   0.10686439]
 [ 0.07903165  0.07824522  0.03141854 ...  0.09988822  0.03057818
   0.06423865]
 [ 0.05468041  0.          0.02699232 ...  0.          0.01515299
   0.12176439]]
[[ 0.09665309  0.12871623  0.05505208 ...  0.20904553 -0.03814263
   0.1629676 ]
 [ 0.04964072  0.11007217  0.0219388  ...  0.02094456  0.
   0.15249318]
 [ 0.04819381  0.09074914  0.05592908 ...  0.          0.
   0.16346402]
 ...
 [ 0.08320453  0.08528891  0.03103865 ...  0.0413214   0.
   0.07757342]
 [ 0.06419578  0.16581935  0.12709865 ...  0.02227743  0.
   0.07662544]
 [ 0.09086038  0.0568338   0.05381792 ...  0.06177751  0.
   0.00960401]]
[[0.06580785 0.00584808 0.09259682 ... 0.13491347 0.         0.04553179]

[[0.06843757 0.06981727 0.09612533 ... 0.         0.         0.04492841]
 [0.05016895 0.02885334 0.17703064 ... 0.         0.         0.        ]
 [0.07078508 0.04549196 0.05473897 ... 0.03748477 0.         0.03157924]
 ...
 [0.07202668 0.05450813 0.07866581 ... 0.         0.         0.05514551]
 [0.04545335 0.0557463  0.10489902 ... 0.05914853 0.00177376 0.03960818]
 [0.06583683 0.17852029 0.06427864 ... 0.21748576 0.00195866 0.01518082]]
[[ 0.07777847  0.14617753  0.09094039 ...  0.09647669 -0.0114177
   0.07408233]
 [ 0.0379204   0.06620768  0.06009071 ...  0.          0.
   0.05172877]
 [ 0.01273517  0.00763776  0.         ...  0.          0.
   0.03951801]
 ...
 [ 0.06655655  0.09371921  0.03916733 ...  0.02231715  0.
   0.03112144]
 [ 0.08841959  0.0956241   0.290959   ...  0.          0.
   0.07625748]
 [ 0.10230143  0.10906614  0.03825155 ...  0.          0.
   0.10170966]]
[[0.01996887 0.17000906 0.028987   ... 0.09608361 0.         0.18853965]
 [0.         0.16148192 0.      

[[0.05017035 0.05628585 0.0506072  ... 0.1477969  0.         0.05154338]
 [0.0467151  0.12870775 0.13092531 ... 0.03287093 0.0107564  0.        ]
 [0.07391507 0.         0.02060758 ... 0.         0.         0.        ]
 ...
 [0.03419496 0.12559201 0.00653698 ... 0.00707266 0.         0.        ]
 [0.123852   0.0824352  0.0450395  ... 0.         0.         0.08403082]
 [0.05752177 0.16859943 0.04044008 ... 0.00459907 0.         0.0340803 ]]
[[ 0.01600753  0.02348531  0.05782968 ...  0.0046184  -0.03814263
   0.11350661]
 [ 0.08362044  0.          0.0538765  ...  0.0046184   0.
   0.13264573]
 [ 0.01047799  0.04629239  0.00780765 ...  0.          0.
   0.0694731 ]
 ...
 [ 0.09522753  0.08600948  0.0538765  ...  0.          0.
   0.11920964]
 [ 0.07521067  0.09646608  0.0538765  ... -0.03926747 -0.03814263
   0.1598908 ]
 [ 0.01451318  0.          0.         ...  0.          0.
   0.        ]]
[[ 0.00748358  0.09022021  0.19541742 ...  0.07131431  0.00375418
   0.07320832]
 [ 0.01451318  

[[0.07345643 0.0551796  0.14626712 ... 0.10415871 0.00526331 0.05069118]
 [0.04226762 0.08668299 0.09730572 ... 0.02229805 0.         0.01959556]
 [0.089085   0.09240673 0.04416192 ... 0.         0.         0.08361939]
 ...
 [0.0893504  0.         0.08111732 ... 0.         0.         0.04051223]
 [0.04887839 0.09427503 0.11027265 ... 0.         0.         0.00866444]
 [0.04393766 0.06293342 0.10335439 ... 0.0673936  0.         0.09964541]]
[[0.02581388 0.         0.         ... 0.         0.         0.        ]
 [0.10980071 0.2883686  0.24849713 ... 0.18009067 0.04763567 0.1421088 ]
 [0.08812805 0.0709439  0.06830207 ... 0.13822992 0.         0.05255311]
 ...
 [0.09318925 0.25043175 0.15756845 ... 0.16462342 0.00841808 0.10137976]
 [0.11294544 0.15546188 0.20317507 ... 0.17160483 0.         0.01061963]
 [0.07012768 0.20425957 0.14754516 ... 0.12744273 0.         0.10481592]]
[[0.0017287  0.06895766 0.05115145 ... 0.03501971 0.         0.10133854]
 [0.07697028 0.07942533 0.07328012 ... 

[[ 0.05561338  0.05262516  0.10816484 ...  0.06642041  0.
   0.01112179]
 [ 0.06144081  0.17571536  0.176512   ...  0.04806753 -0.03814263
   0.01866371]
 [ 0.03911031  0.11970982  0.1654172  ...  0.11789382  0.
   0.04096813]
 ...
 [ 0.04065568  0.11191908  0.23017581 ...  0.11045273  0.
   0.08690103]
 [ 0.04471036  0.14840789  0.11455336 ...  0.08404306  0.
   0.02397155]
 [ 0.11263941  0.0903004   0.17777105 ...  0.09569976  0.
   0.        ]]
[[ 0.05993355  0.12392569  0.147448   ...  0.04153068  0.
   0.10165834]
 [ 0.08064657  0.11924526  0.15286708 ...  0.08687355  0.
   0.        ]
 [ 0.07163597  0.07812813  0.19374567 ...  0.05039162  0.
   0.        ]
 ...
 [ 0.06199264  0.11283135  0.07288831 ...  0.05539682  0.
   0.03141887]
 [ 0.06594267  0.03984115  0.0480254  ...  0.08182904  0.
   0.12793916]
 [ 0.06611731  0.14067459  0.10769299 ...  0.04021078 -0.03814263
   0.07242028]]
[[0.12112408 0.16098742 0.17425781 ... 0.01187832 0.         0.04158071]
 [0.02926079 0.077186  

[[ 0.09945538  0.09084766  0.1004021  ...  0.05895413  0.
   0.11914801]
 [ 0.13343984  0.09083916  0.16458474 ...  0.02137035  0.
   0.02543291]
 [ 0.06812619  0.03907299  0.0427472  ...  0.          0.
   0.02423102]
 ...
 [ 0.07600529  0.13988093  0.04892018 ...  0.0433143   0.
   0.04623434]
 [ 0.06688736  0.09255444  0.08727447 ... -0.0058067  -0.03814263
  -0.00260974]
 [ 0.07280605  0.1519391   0.00352008 ...  0.05165899  0.
   0.07475612]]
[[ 0.11295761  0.07226086  0.02370101 ...  0.01778534  0.00213842
  -0.0023117 ]
 [ 0.04102622  0.          0.05310618 ...  0.          0.
   0.        ]
 [ 0.04509727  0.          0.03029813 ...  0.          0.
   0.        ]
 ...
 [ 0.11332565  0.11935278  0.05459769 ...  0.          0.
   0.        ]
 [ 0.11402889  0.1296075   0.09298877 ...  0.00969966  0.
   0.        ]
 [ 0.05255849  0.11842152  0.03410666 ...  0.03952979 -0.03814263
  -0.02892261]]
[[ 0.09932129  0.11208988  0.17278774 ...  0.09240451  0.
   0.07553959]
 [ 0.06032992  

[[0.03793045 0.08682681 0.08901972 ... 0.03446769 0.         0.10349153]
 [0.02673325 0.07992407 0.08748668 ... 0.00187539 0.         0.02566   ]
 [0.09263825 0.0770428  0.07573321 ... 0.02224947 0.         0.02097924]
 ...
 [0.06969931 0.12152352 0.08123847 ... 0.03185687 0.         0.01080466]
 [0.06945748 0.0776144  0.02764826 ... 0.01861337 0.         0.13698232]
 [0.10845853 0.1699786  0.06751399 ... 0.13901927 0.         0.06181168]]
[[ 0.1106954   0.08386041  0.14247519 ...  0.01625244  0.
   0.04649177]
 [ 0.06458858  0.05956411  0.07210727 ...  0.02052599  0.
   0.        ]
 [ 0.0622832   0.10056836  0.07399541 ...  0.00545937  0.01829442
   0.03494282]
 ...
 [ 0.08831337  0.11028055  0.08760551 ...  0.03053238 -0.03814263
   0.01975989]
 [ 0.0617454   0.08574567  0.09639127 ...  0.06349754  0.
   0.08175956]
 [ 0.10821463  0.08173338  0.09240617 ...  0.07521322  0.
   0.04987996]]
[[0.08415671 0.15361328 0.08089235 ... 0.         0.         0.08867638]
 [0.04434554 0.15707144

[[0.12392396 0.11880558 0.12190828 ... 0.1120991  0.         0.09380836]
 [0.06118733 0.14537719 0.08816288 ... 0.00444017 0.         0.1621245 ]
 [0.11029758 0.13086055 0.07701958 ... 0.08804632 0.00227666 0.18870182]
 ...
 [0.07097587 0.13994098 0.0931429  ... 0.03783464 0.         0.09264551]
 [0.04415916 0.06713407 0.1014476  ... 0.08705615 0.         0.15970312]
 [0.01806481 0.0613388  0.06986698 ... 0.         0.         0.06734348]]
[[ 4.37906012e-02  1.55550569e-01  1.19916104e-01 ...  1.22907661e-01
  -3.81426290e-02  5.69200926e-02]
 [ 8.22899416e-02  9.01701823e-02  1.31060898e-01 ...  4.26522605e-02
   0.00000000e+00  6.03013001e-02]
 [ 6.29884526e-02  1.86794370e-01  1.17495142e-01 ...  2.08549067e-01
   0.00000000e+00  1.41395047e-01]
 ...
 [ 1.76530462e-02  6.77386746e-02  1.76944988e-04 ...  0.00000000e+00
   0.00000000e+00  1.26175165e-01]
 [ 2.15339139e-02  5.64740337e-02  4.90193851e-02 ...  0.00000000e+00
   0.00000000e+00  5.78501113e-02]
 [ 1.19557399e-02  1.54545

[[0.10107452 0.13827176 0.06173208 ... 0.00811141 0.         0.        ]
 [0.13318434 0.1267352  0.03514432 ... 0.04921711 0.         0.00600229]
 [0.17701821 0.14027941 0.04177975 ... 0.00848623 0.         0.05774042]
 ...
 [0.14485693 0.06352241 0.04966418 ... 0.03114488 0.         0.02096631]
 [0.14082766 0.12605351 0.05284642 ... 0.         0.         0.08847227]
 [0.13257931 0.13260937 0.0745487  ... 0.03331875 0.         0.        ]]
[[0.06704247 0.00959159 0.12021411 ... 0.         0.         0.03134554]
 [0.05724006 0.13433735 0.24181752 ... 0.13105579 0.01935864 0.05756753]
 [0.07231746 0.05711694 0.13992158 ... 0.         0.         0.02794782]
 ...
 [0.         0.04153308 0.00275494 ... 0.         0.         0.00805364]
 [0.04430659 0.04306128 0.02300135 ... 0.         0.         0.        ]
 [0.         0.         0.05816764 ... 0.         0.         0.00202363]]
[[ 0.12948716  0.13279553  0.14255288 ...  0.06134102  0.
   0.00387383]
 [ 0.09245121  0.16415879  0.12082583 .

In [34]:
print(len(Para_Embeddings))

456


In [35]:
Paragraph_Embeddings = np.array(Para_Embeddings)

C:\Users\arazs\.conda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [36]:
np.save('Para_Embeddings_Infersent3.npy', Paragraph_Embeddings)

In [37]:
check_array = np.load('Para_Embeddings_Infersent3.npy', allow_pickle=True)

In [38]:
print(check_array[1].shape)

(14, 4096)


In [39]:
Q_Embeddings = []

for para in data_qs:
  para_embed = model.encode(para)
  print((para_embed))
  Q_Embeddings.append(para_embed)




[[0.06627975 0.04655779 0.07002031 ... 0.0425627  0.         0.06501141]
 [0.11186916 0.07775531 0.07010239 ... 0.         0.         0.01484449]
 [0.09156413 0.12611075 0.05272425 ... 0.01422109 0.         0.06497912]
 ...
 [0.14173077 0.1225329  0.14800398 ... 0.         0.         0.04248734]
 [0.08382923 0.17260209 0.08855174 ... 0.25468647 0.         0.02992734]
 [0.02504111 0.04743883 0.01561173 ... 0.         0.         0.01976585]]
[[0.08066359 0.1353543  0.05852262 ... 0.11620369 0.         0.        ]
 [0.10301598 0.12922329 0.07888107 ... 0.         0.         0.00585315]
 [0.07775934 0.07566264 0.08255339 ... 0.00387252 0.         0.01561254]
 ...
 [0.07279599 0.12368789 0.03516949 ... 0.03919126 0.         0.        ]
 [0.06929786 0.17442983 0.07413388 ... 0.04054999 0.         0.        ]
 [0.16019036 0.20578589 0.10959235 ... 0.08507206 0.         0.03351867]]
[[ 0.01632037  0.02736228  0.         ...  0.          0.
   0.04724886]
 [ 0.09003712  0.0980235   0.07948296 .

[[ 0.03173562  0.09216751  0.         ...  0.          0.01434752
   0.01750803]
 [ 0.04458864  0.12869051  0.10070822 ...  0.          0.
   0.01984805]
 [ 0.04685447  0.11068521  0.04997679 ...  0.16684431  0.
   0.01264489]
 ...
 [ 0.06529259  0.02870159  0.05120734 ...  0.00971686  0.
   0.00100518]
 [ 0.06727946  0.09792174  0.16084677 ...  0.10339686  0.
   0.        ]
 [ 0.06979549  0.11192173  0.17690404 ... -0.02954776 -0.03814263
   0.04692173]]
[[ 0.02159104  0.          0.         ...  0.          0.
   0.0671047 ]
 [ 0.03837072  0.          0.         ...  0.          0.
   0.03671401]
 [ 0.01895716  0.05664489 -0.03044512 ... -0.00096264 -0.03814263
   0.10033928]
 [ 0.07114334  0.02387922  0.         ...  0.          0.
   0.09247257]]
[[ 0.13249025  0.10960729  0.06634167 ...  0.05228628  0.
   0.08142243]
 [ 0.04413019  0.12488658  0.12994532 ... -0.03814677 -0.02535659
   0.00412765]
 [ 0.04151847  0.03883175  0.00734278 ...  0.04538458  0.
   0.02564886]
 ...
 [ 0.15

[[ 0.01007904  0.0322711   0.1183934  ...  0.          0.
   0.05556179]
 [ 0.02026472  0.04168938  0.09457808 ...  0.          0.
   0.06697952]
 [ 0.06353511  0.01353062  0.10208019 ...  0.05456854 -0.03814263
   0.01911205]]
[[ 0.10145038  0.11161226  0.06899521 ...  0.          0.
   0.        ]
 [ 0.08053312  0.10631149  0.09951525 ...  0.          0.
   0.        ]
 [ 0.04217203  0.07279117  0.14400625 ...  0.01432546 -0.03814263
   0.02983982]]
[[ 0.03157219  0.13812606  0.         ...  0.          0.03023988
   0.06074409]
 [ 0.07329272  0.10669613  0.09011748 ...  0.          0.
   0.09363902]
 [ 0.13347553  0.07632892  0.11345405 ...  0.03969083 -0.03814263
   0.03759957]]
[[ 0.07809937  0.17128935  0.02821385 ...  0.16769075  0.
   0.00450148]
 [ 0.0832277   0.08421261  0.         ...  0.03088002  0.
   0.        ]
 [ 0.0617738   0.12686026  0.06269103 ...  0.0168167   0.05240979
   0.        ]
 ...
 [ 0.03343156  0.12744208  0.08605783 ...  0.08168688  0.
   0.00479644]
 [ 

[[ 0.05300374  0.05591983  0.         ...  0.03987539  0.
   0.05373681]
 [ 0.07667299  0.01976141  0.05938672 ...  0.          0.
   0.        ]
 [ 0.09003712  0.          0.         ...  0.          0.
   0.00287599]
 ...
 [ 0.07114334  0.08464637  0.07861197 ...  0.01123654 -0.03814263
  -0.00295824]
 [ 0.06250834  0.20072734  0.08457047 ...  0.19596282  0.
   0.04943905]
 [ 0.00940901  0.12412451  0.06859569 ...  0.02736828  0.
   0.01442275]]
[[0.07417694 0.14874792 0.09654512 ... 0.06299321 0.         0.00937413]
 [0.07256025 0.09971236 0.01580969 ... 0.05802655 0.         0.06150896]
 [0.01941251 0.11255644 0.03079727 ... 0.02640027 0.01396959 0.08744604]
 ...
 [0.01524751 0.         0.02077509 ... 0.09115916 0.         0.        ]
 [0.05962299 0.12360836 0.07291803 ... 0.078871   0.         0.03035315]
 [0.04342872 0.06613174 0.08894566 ... 0.03875257 0.         0.02539873]]
[[ 0.04982885  0.04058081  0.         ...  0.          0.
   0.00256221]
 [ 0.05344677  0.03990749  0.05

[[ 0.15150896  0.10291563  0.03500805 ...  0.          0.
   0.02359217]
 [ 0.07207908  0.09522096  0.14592089 ...  0.13398752  0.
   0.02296963]
 [ 0.09836628  0.06381019  0.07119966 ...  0.          0.
   0.        ]
 ...
 [ 0.17918319  0.08518815  0.07098196 ...  0.          0.
   0.03673914]
 [ 0.10243385  0.07660881  0.14322399 ...  0.09158746 -0.03814263
   0.01476945]
 [ 0.13987933  0.11013117  0.07684769 ...  0.          0.
   0.01551802]]
[[ 5.3327952e-02  9.5218092e-02  6.4017378e-02 ...  6.9535375e-03
   0.0000000e+00  1.5249219e-02]
 [ 9.4277514e-03  2.9145794e-02  1.3115865e-01 ...  0.0000000e+00
   0.0000000e+00  1.0489316e-02]
 [ 8.9370176e-02  5.1442657e-02  1.4026920e-01 ...  0.0000000e+00
   0.0000000e+00  1.2857854e-04]
 [ 4.9925152e-02  1.1461518e-01  5.0014466e-02 ... -3.9267469e-02
  -1.9920705e-02  3.2906212e-02]
 [ 4.4792347e-02  1.3729808e-01  6.0924899e-02 ...  1.3428076e-01
   0.0000000e+00  2.0374980e-02]
 [ 6.1692465e-02  4.8180696e-02  1.4276721e-02 ...  2

[[0.03343156 0.10948248 0.         ... 0.         0.         0.15113664]
 [0.04309453 0.15076254 0.07559121 ... 0.01686878 0.         0.15723088]
 [0.09081831 0.09603002 0.13509676 ... 0.06927205 0.         0.03829176]
 ...
 [0.02843451 0.05203906 0.         ... 0.06387961 0.         0.17326549]
 [0.05263202 0.09219679 0.0285462  ... 0.         0.         0.148953  ]
 [0.08268131 0.12742305 0.04157293 ... 0.01100557 0.         0.17096913]]
[[ 0.07389969  0.08535034  0.07112984 ...  0.02105666  0.
   0.05138398]
 [ 0.11996447  0.114215    0.0729873  ...  0.04037883 -0.03814263
   0.00972321]
 [ 0.15150897  0.08322357  0.10233208 ...  0.10289688  0.00416681
   0.0040119 ]
 [ 0.10902032  0.13066277  0.07686562 ...  0.02542     0.
   0.01293789]
 [ 0.14162464  0.09306968  0.06827569 ...  0.01904304  0.
   0.0473261 ]]
[[0.07114334 0.05567059 0.01598403 ... 0.         0.         0.06787394]
 [0.05013305 0.         0.         ... 0.         0.         0.04738241]
 [0.05104648 0.08418307 0.10

[[ 0.07620079  0.07506226  0.         ...  0.          0.
   0.17277916]
 [ 0.08140357  0.10119805  0.05661654 ... -0.00082205 -0.01744591
   0.17381543]
 [ 0.04403833  0.03598535  0.18847811 ...  0.          0.
   0.13569473]
 [ 0.06369846  0.08391801  0.         ...  0.          0.
   0.1590965 ]
 [ 0.0617738   0.15121946  0.         ...  0.12674351  0.
   0.07365263]]
[[ 0.02868508  0.11153203  0.14993584 ...  0.0560514  -0.03814263
   0.01127777]
 [ 0.06916153  0.08287334  0.03018649 ...  0.05763013  0.
   0.01883095]
 [ 0.08562663  0.05152942  0.09090939 ...  0.0262457   0.
   0.01513827]]
[[ 0.07888915  0.08971709  0.10774527 ...  0.          0.
   0.07925981]
 [ 0.05236921  0.08256136  0.01727569 ...  0.          0.
   0.00519839]
 [ 0.07114332  0.14158894  0.0682085  ...  0.00719052  0.
   0.07560663]
 ...
 [ 0.16848253  0.06263439  0.12812543 ...  0.04023845  0.
   0.08893317]
 [ 0.18572819  0.11179349  0.1314671  ... -0.0085478  -0.03545617
   0.03717676]
 [ 0.04881641  0.114

[[ 0.01226579  0.27362257  0.06377173 ... -0.03926747 -0.02390192
   0.04384596]
 [ 0.0356605   0.27697948  0.01646505 ... -0.03926747 -0.03814263
   0.05003311]
 [ 0.03454137  0.22555345  0.         ...  0.          0.
   0.02767276]
 ...
 [ 0.05048195  0.04887443  0.01173443 ...  0.          0.
   0.04159523]
 [ 0.02159102  0.          0.0179011  ...  0.          0.
   0.03501825]
 [ 0.06489234  0.21357061  0.01609065 ... -0.03926747 -0.03814263
   0.04363533]]
[[0.00550837 0.01052829 0.         ... 0.06360503 0.         0.09976957]
 [0.12537196 0.1423484  0.03250301 ... 0.02268369 0.         0.0365627 ]
 [0.08593946 0.20075426 0.         ... 0.         0.         0.05219813]
 ...
 [0.09308328 0.07302175 0.04886967 ... 0.02647474 0.         0.03203397]
 [0.04113867 0.19835971 0.08027578 ... 0.21818614 0.         0.08730529]
 [0.11011806 0.09714703 0.14145981 ... 0.15911312 0.06137686 0.00289412]]
[[ 0.10258454  0.15203892  0.05229083 ...  0.15308522  0.
   0.17286398]
 [ 0.08321133  

[[ 0.02564886  0.04058081  0.         ...  0.          0.
   0.00788738]
 [ 0.07434969  0.04861483  0.05424005 ...  0.02815224 -0.01703992
   0.04948805]
 [ 0.07735105  0.05541923  0.06424347 ...  0.02967485  0.
   0.0514066 ]
 [ 0.05130573  0.05090978  0.06974038 ...  0.05062452 -0.03814263
   0.02944685]
 [ 0.07735105  0.05541923  0.06424347 ...  0.02499789  0.
   0.0477032 ]]
[[ 0.          0.03387157  0.         ...  0.          0.
   0.09125646]
 [ 0.05602248  0.09714116  0.05528664 ...  0.05456082  0.
   0.01739499]
 [ 0.05841807  0.08285277  0.13336508 ...  0.06544504 -0.03814263
   0.04561824]
 [ 0.00527628  0.0376181   0.         ...  0.05577895  0.
   0.05016246]]
[[0.07199311 0.18003671 0.0149891  ... 0.00937223 0.         0.        ]
 [0.059259   0.16083872 0.12292363 ... 0.00028904 0.03010238 0.        ]
 [0.0870495  0.14211103 0.         ... 0.02677028 0.         0.02364929]
 ...
 [0.02189248 0.12242528 0.         ... 0.13480477 0.         0.        ]
 [0.02614664 0.13427

[[0.03696789 0.01236804 0.07418466 ... 0.02858679 0.         0.        ]
 [0.07775934 0.02201398 0.02475562 ... 0.04421211 0.         0.03476343]
 [0.12404457 0.12153333 0.0647569  ... 0.01909179 0.         0.14905997]
 ...
 [0.05771952 0.         0.07418466 ... 0.         0.         0.        ]
 [0.04001756 0.07624251 0.         ... 0.02032385 0.         0.1637127 ]
 [0.04107358 0.0653624  0.02106971 ... 0.         0.         0.14224108]]
[[ 0.05549705  0.1171449   0.08897498 ...  0.          0.
   0.0207316 ]
 [ 0.02881173  0.11205894  0.         ...  0.01118491  0.
   0.01847043]
 [ 0.09982835  0.09618534  0.06485995 ...  0.07235717  0.
   0.        ]
 [ 0.00878809  0.1171449   0.07498767 ...  0.          0.
   0.02471139]
 [ 0.03907556  0.12569548  0.11771489 ...  0.0169308  -0.00451707
   0.0450824 ]]
[[0.08008029 0.         0.01497861 ... 0.12769723 0.         0.04828902]
 [0.16147186 0.12858838 0.13472793 ... 0.22036435 0.         0.1369198 ]
 [0.01941251 0.05267905 0.00413509 .

[[0.11117041 0.03821736 0.06343422 ... 0.00404993 0.         0.03174226]
 [0.09003708 0.         0.04850646 ... 0.         0.         0.01258892]
 [0.09238376 0.0297746  0.05106713 ... 0.         0.         0.0135464 ]
 ...
 [0.03343156 0.04669783 0.         ... 0.         0.00115671 0.02854908]
 [0.05826584 0.         0.18767247 ... 0.         0.         0.04445225]
 [0.11117041 0.03071087 0.0401309  ... 0.00404993 0.         0.01422555]]
[[ 0.07114334  0.08806182  0.0310647  ...  0.          0.
   0.01283672]
 [ 0.06669743  0.15543917  0.05970967 ...  0.03382827 -0.01144327
   0.09298773]
 [ 0.07551342  0.17158772  0.07418466 ...  0.00707409 -0.00543915
   0.08270263]]
[[0.06177381 0.13329358 0.02525002 ... 0.03019134 0.         0.1183026 ]
 [0.11270054 0.08483559 0.07482212 ... 0.         0.         0.04508234]
 [0.06197955 0.05119183 0.14112806 ... 0.0248288  0.         0.08813535]
 ...
 [0.0544572  0.03890159 0.04525061 ... 0.03896847 0.         0.        ]
 [0.09003712 0.05925372

[[ 0.01933094  0.07321903  0.02430796 ...  0.14190383 -0.03814263
  -0.02001402]
 [ 0.08351782  0.          0.04440474 ...  0.          0.
   0.02204387]
 [ 0.0445766   0.09611701  0.04078171 ...  0.12673901 -0.03814263
   0.01101605]
 ...
 [ 0.05918539  0.12677248  0.05633943 ...  0.          0.
   0.01073785]
 [ 0.03180593  0.0968334   0.00933237 ...  0.13204093  0.
   0.01740485]
 [ 0.01576508  0.05836684  0.06678221 ...  0.0448571   0.
   0.00677988]]
[[0.09141967 0.12217829 0.0456113  ... 0.         0.         0.07409814]
 [0.03961387 0.06370214 0.         ... 0.         0.         0.12928809]
 [0.07114332 0.12579761 0.04446823 ... 0.10001923 0.         0.07136627]
 ...
 [0.09616974 0.09241473 0.         ... 0.04290899 0.00392395 0.07572491]
 [0.09616974 0.06179831 0.         ... 0.         0.         0.07572491]
 [0.08826429 0.12386584 0.         ... 0.13517807 0.         0.06827687]]
[[ 0.03353504  0.01230993  0.07294226 ...  0.          0.
   0.02502913]
 [ 0.05466356  0.127620

[[ 0.08277006  0.0865342   0.0621785  ...  0.          0.
   0.        ]
 [ 0.09156413  0.13288322  0.04754326 ...  0.0157565   0.
   0.        ]
 [ 0.04635864  0.1047304   0.02782537 ...  0.01122386  0.0034875
  -0.02212642]
 ...
 [ 0.09238376  0.10342929  0.05106713 ...  0.04587781  0.
   0.02562151]
 [ 0.02070583  0.13097629  0.04039308 ...  0.00721704  0.
   0.        ]
 [ 0.04496132  0.11769993  0.         ...  0.0652863   0.
   0.        ]]
[[ 0.05186008  0.07640221  0.12352415 ...  0.11277725 -0.01505992
   0.0160565 ]
 [ 0.03935695  0.07128941  0.15934573 ...  0.12628295  0.
   0.05716055]
 [ 0.0434287   0.14188783  0.05210837 ...  0.08038703  0.
   0.01644943]
 [ 0.01894291  0.09912343  0.01580291 ...  0.          0.
   0.00805881]
 [ 0.06044814  0.10729153  0.07745723 ...  0.00396513  0.
   0.07453727]]
[[0.09003712 0.07858633 0.         ... 0.         0.         0.1104998 ]
 [0.10606524 0.01084122 0.         ... 0.04524766 0.         0.06547506]
 [0.0346075  0.09361579 0.032

[[0.04352307 0.11598684 0.         ... 0.         0.0150005  0.06621198]
 [0.05409632 0.03545508 0.0651271  ... 0.         0.00431162 0.03565285]
 [0.07487512 0.0529888  0.         ... 0.         0.         0.04797276]
 ...
 [0.07311465 0.05542037 0.10773794 ... 0.02531034 0.         0.0170651 ]
 [0.03021101 0.         0.05375993 ... 0.         0.         0.09620247]
 [0.10540839 0.06556114 0.0525148  ... 0.         0.         0.0365858 ]]
[[ 0.08315033  0.04396246  0.01815316 ...  0.          0.
   0.02453459]
 [ 0.02328202  0.10590993  0.05465277 ...  0.02005086 -0.03717192
   0.13903214]
 [ 0.03734579  0.06286772  0.03247958 ...  0.          0.00280936
   0.14587803]]
[[ 0.07031547  0.05591259  0.1340967  ...  0.01307009  0.
   0.01567021]
 [ 0.09003712  0.13858871  0.00547382 ...  0.05166491  0.00683207
   0.04176223]
 [ 0.07537688  0.15958047  0.09778088 ...  0.          0.
   0.00645664]
 [ 0.04881757  0.14235605  0.06621151 ...  0.10687183 -0.03814263
   0.02693008]
 [ 0.0149334

[[ 0.0805482   0.07451002  0.03408333 ...  0.          0.
   0.00839423]
 [ 0.07114334  0.09267072  0.10451204 ... -0.03926747 -0.03814263
   0.09783616]
 [ 0.07114334  0.20017706  0.07581    ...  0.18348871  0.
   0.00959166]
 [ 0.05318708  0.10305625  0.11283559 ...  0.          0.
   0.        ]]
[[0.03637556 0.08851351 0.07838815 ... 0.         0.         0.1316016 ]
 [0.07516103 0.04787667 0.06063253 ... 0.09138509 0.         0.02071703]
 [0.07065429 0.06558535 0.10006973 ... 0.03554178 0.         0.        ]
 ...
 [0.01977862 0.01362428 0.032523   ... 0.         0.         0.04188594]
 [0.081066   0.22277474 0.11076418 ... 0.23754407 0.         0.03138346]
 [0.08147588 0.04256573 0.10708854 ... 0.04538458 0.         0.01296386]]
[[ 0.10821542  0.18292594  0.02283493 ...  0.10482865  0.
   0.04950527]
 [ 0.06008885  0.12003293  0.01004253 ...  0.          0.
   0.12131746]
 [ 0.11651399  0.18000439  0.08609786 ...  0.06148412 -0.03814263
   0.04572215]
 [ 0.05348608  0.09628938  0

[[ 0.03637554  0.08851351  0.0516024  ...  0.          0.
   0.03880672]
 [ 0.05990421  0.06636301  0.05097708 ...  0.07103761 -0.03814263
   0.08075007]
 [ 0.14150773  0.08579043  0.02032562 ...  0.          0.
   0.10288829]
 ...
 [ 0.07114332  0.08806182  0.1116538  ...  0.05021518  0.
   0.19492368]
 [ 0.07114332  0.12645967  0.06265218 ...  0.00902551  0.
   0.00367806]
 [ 0.02696974  0.08730073  0.00034711 ...  0.          0.
   0.17102487]]
[[ 0.08686671  0.0752152   0.1041049  ...  0.          0.
   0.02564743]
 [ 0.07114333  0.17411616  0.05137211 ...  0.03084748  0.
   0.        ]
 [ 0.06988297  0.20359334  0.01297865 ...  0.09972361  0.
   0.01350969]
 [ 0.06272721  0.05079967  0.         ...  0.01338771  0.
   0.        ]
 [ 0.09003712  0.22906196  0.08204704 ... -0.00989484  0.00739159
   0.02872475]
 [ 0.02607578  0.19679809  0.01116144 ...  0.07156838  0.
   0.08651815]]
[[ 0.08932779  0.1573599   0.00225355 ...  0.          0.
   0.10464168]
 [ 0.075641    0.02048706  0

[[0.08770816 0.03398713 0.         ... 0.         0.         0.03828231]
 [0.00423099 0.05342282 0.07847358 ... 0.0360118  0.         0.02644795]
 [0.14585115 0.08826422 0.13375045 ... 0.06167447 0.         0.00198737]
 ...
 [0.09269529 0.09004247 0.0769484  ... 0.03169279 0.         0.1021404 ]
 [0.03656468 0.11790802 0.00373643 ... 0.01296579 0.         0.        ]
 [0.15450796 0.08771739 0.07146907 ... 0.00189198 0.         0.02742356]]
[[ 0.10259758  0.03281106  0.07464797 ...  0.06662626  0.07394259
   0.08175821]
 [ 0.08772116  0.04621708  0.09978564 ...  0.          0.
   0.02507327]
 [ 0.09003708  0.08715352  0.         ...  0.          0.
   0.06150896]
 ...
 [ 0.03343156  0.09290916  0.00775267 ...  0.          0.
   0.06653184]
 [ 0.03300137  0.02748258  0.         ...  0.          0.
   0.11596915]
 [ 0.09424239  0.02104906  0.09327177 ...  0.03366346 -0.03814263
   0.02921575]]
[[0.04148835 0.12478585 0.06683551 ... 0.02254524 0.         0.01512298]
 [0.10895157 0.11531456

[[ 0.05353539  0.09683458  0.02234122 ...  0.02943906  0.
   0.09413849]
 [ 0.07066973  0.11655799  0.13515593 ... -0.00612784 -0.03814263
   0.04095376]
 [ 0.01516614  0.10038099  0.01477407 ...  0.          0.
   0.01339893]
 [ 0.04848839  0.06791589  0.05016472 ...  0.02712856  0.00349842
   0.07549139]]
[[ 0.09156413  0.1117935   0.04754326 ...  0.          0.
   0.07842495]
 [ 0.10967306  0.03544617  0.03685849 ...  0.          0.
   0.0054926 ]
 [ 0.1066189   0.05801387  0.01757628 ...  0.          0.
   0.104883  ]
 ...
 [ 0.04648329  0.04418255  0.01589621 ...  0.          0.
   0.12143455]
 [ 0.07111893  0.02545537  0.07413802 ... -0.03926747  0.0054794
   0.11519741]
 [ 0.08804698  0.02111919  0.02150937 ...  0.01784675  0.
   0.00592178]]
[[ 0.08178151  0.05567956  0.09617513 ...  0.05883597  0.
   0.04096163]
 [ 0.09515554  0.161055    0.13924554 ... -0.0169606  -0.03814263
   0.01617771]
 [ 0.13838078  0.11570881  0.0903574  ...  0.06533137  0.
   0.01719976]
 [ 0.11223384

[[0.03421977 0.09342144 0.23584792 ... 0.         0.         0.17166698]
 [0.02213759 0.02931744 0.04278149 ... 0.         0.         0.13140386]
 [0.05017463 0.06384747 0.09437224 ... 0.         0.         0.        ]
 ...
 [0.09616977 0.         0.07879858 ... 0.04370721 0.         0.00990985]
 [0.06577723 0.04958779 0.00424515 ... 0.04413179 0.         0.02774111]
 [0.06539159 0.06229097 0.07341633 ... 0.         0.         0.03190583]]
[[0.0806599  0.05777797 0.00891979 ... 0.0803638  0.         0.06270818]
 [0.04683187 0.05557464 0.01270175 ... 0.         0.         0.0429078 ]
 [0.00055549 0.12571706 0.00332958 ... 0.0173787  0.00718118 0.01396539]
 ...
 [0.         0.13100274 0.         ... 0.         0.         0.1904484 ]
 [0.0297482  0.1418321  0.10328512 ... 0.         0.         0.05523448]
 [0.04014434 0.08966478 0.04154347 ... 0.01896987 0.         0.20150523]]
[[ 0.09246039  0.0490857   0.05448968 ...  0.03557255  0.
   0.04627628]
 [ 0.14250368  0.1090838   0.07564347 .

[[ 0.113887    0.          0.         ...  0.          0.
   0.06932382]
 [ 0.06456821  0.09522096  0.10951977 ...  0.07094729 -0.03814263
   0.01549171]
 [ 0.08804822  0.09315733  0.         ...  0.01135743  0.
   0.        ]
 ...
 [ 0.14496757  0.          0.1173123  ...  0.          0.
   0.02166515]
 [ 0.05632941  0.          0.09540622 ...  0.          0.
   0.00726371]
 [ 0.04428947  0.02867295  0.         ...  0.          0.
   0.        ]]
[[ 0.05208988  0.01924101  0.07240242 ... -0.03090075 -0.02894576
   0.13289425]
 [ 0.06708057  0.19233204  0.03818626 ...  0.06971421  0.02829693
   0.07551895]
 [ 0.03316654  0.13136932  0.01266835 ...  0.13965413  0.
   0.09951881]]
[[ 0.06077174  0.08449056  0.0342869  ...  0.05026966  0.
   0.0149966 ]
 [ 0.09230419  0.16267814 -0.01629366 ... -0.02054783  0.03472597
   0.00750871]
 [ 0.04540374  0.07106455  0.         ...  0.          0.
   0.03053641]
 [ 0.03559977  0.07926522  0.01562377 ...  0.03211706  0.
   0.02331045]]
[[ 0.040541

In [40]:
print(len(Q_Embeddings))
Question_Embeddings = np.array(Q_Embeddings)
np.save('Ques_Embeddings_Infersent3.npy', Question_Embeddings)

456


C:\Users\arazs\.conda\envs\pytorch\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


In [41]:
check_array2 = np.load('Ques_Embeddings_Infersent3.npy', allow_pickle=True)

In [42]:
print(check_array2[1].shape)

(12, 4096)
